[custom.all.idris2-techtalk]
type = "local"
path = "."
ipkg = "idris2-techtalk.ipkg"
test = "test/test.ipkg"

[custom.all.idris2-techtalk-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[idris2]
repl.rlwrap = true
